[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tve1n", email = 'timarumak@gmail.com'}
]
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "psycopg>=3.2.10",
]
